name: Debug build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RELEASE_FIT_DOWNSAMPLE: ${{ github.event.inputs.downsample_factor || '1' }}

jobs:
  build-release:
    name: Build gnomon binary
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Cache cargo build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build gnomon (release)
        run: |
          set -euxo pipefail
          CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true cargo +nightly build --release --bin gnomon

      - name: Upload gnomon binary
        uses: actions/upload-artifact@v4
        with:
          name: gnomon-release-binary
          path: target/release/gnomon
